# Header Menu
menu:
  Home: /
  Research: /research/
  People: /people/
  Achievements: /categories/Publication/
  Openings: /openings/
  Contact: /contact/
   
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true # whether or not to load the fancybox library

# Integrations
disqus_shortname: 
google_analytics:
swiftype_install_key: 
google_api_key: AIzaSyBJQ8sEcJSnPYzILK6O6eH75Jz3JDOlvEo

# Social
social:
  twitter: http://www.twitter.com
  facebook: http://www.facebook.com
  linkedin: http://www.linkedin.com

# Miscellaneous
color_scheme: turquoise   # options: blue, gray, green, orange, red, turquoise
favicon: /favicon.ico # path from root of hexo site
default_author: Anonymous

about: Flexible Electronics Group
description: Flexible Electronics Group at POSTECH
professor:
  name: Yoonyoung Chung
  phone: +82-54-279-2225
  email: ychung@postech.ac.kr

group_admin:
  name: Chaehyun Lee
  phone: +82-54-279-8092
  email: sms1621@postech.ac.kr

phone: +82-54-279-8092
email: sms1621@postech.ac.kr
address_1: "LG Building #203, 77 Cheongam-ro"
address_2: Nam-gu, Pohang
address_3: Gyeongbuk, 37673, Republic of Korea
skype:
lat: 36.011495
long: 129.320422

banners:
  - src: /assets/images/banners/banner-1.jpg
  - src: /assets/images/banners/banner-3.jpg
news:
  - message: |
      Inyeol wins an excellence award at the 5th Bio Startup Idea Competition (http://biostartup.jobkorea.co.kr). Congratulations!
      (May. 2018)

      Taewon joins our group. Welcome!
      (Feb. 2018)

      Seongmin and Hyuk gives excellent presentations about their research on flexible devices at the 2017 MRS Fall Meeting in Boston.
      (Nov. 2017)

      Inyeol and Jinpyo exhibits their work on the wearable sensor platform to prevent Sudden Infant Death Syndrome at the Tech Fair organized by the Center for Advanced Soft Electronics. Well done!
      (Nov. 2017)

      Prof. Chung gives a special lecture on e-paper technologies at the LG Display Technical Talk.
      (Jun. 2017)
  - message: |
      Jinpyeo, an undergraduate intern, gets early admission to POSTECH. He will join our graduate program in Spring 2018. Congratulations!
      (Jan. 2017)

      A team of Prof. Yoonyoung Chung (Co-PI), Prof. Ho-Jin Song (PI), and Prof. Wonbin Hong (Co-PI) at POSTECH EE is chosen as the recipient of the prestigious ICT research award from Samsung Future Technology Foundation. The groundbreaking research aims to develop massive MIMO beamforming technologies with flexible electronics.
      (Sep. 2016)

      Seongmin joins our group. Welcome!
      (Sep. 2016)

      Two graduate students Inyeol and Hyuk joins our group. Let's celebrate a new beginning!
      (Mar. 2016)

      Professor Yoonyoung Chung joins the EE department at POSTECH as an assistant professor.
      (Feb. 2015)

sponsors:
  - url: http://www.moe.go.kr
    img: /assets/images/sponsors/moe.gif
  - url: http://www.msip.go.kr
    img: /assets/images/sponsors/msip.gif
  - url: http://www.msip.go.kr
    img: /assets/images/sponsors/mi.jpg
  - url: http://www.nrf.re.kr
    img: /assets/images/sponsors/nrf.jpg
  - url: http://www.case.re.kr
    img: /assets/images/sponsors/case.jpg
  - url: http://www.posco.com
    img: /assets/images/sponsors/posco.jpg
  - url: http://www.samsungftf.com
    img: /assets/images/sponsors/samsung.jpg
  - url: http://www.lgdisplay.com
    img: /assets/images/sponsors/lgdisplay.jpg
  - url: https://www.keysight.com
    img: /assets/images/sponsors/keysight.jpg
  - url: https://www.ansys.com
    img: /assets/images/sponsors/ansys.jpg
photos:
  - src: /assets/images/team/group/2017_summer.jpg
    caption: 2017 Summer
  - src: /assets/images/team/group/2017_spring.jpg
    caption: 2017 Spring
  - src: /assets/images/team/group/2016_spring.jpg
    caption: 2016 Spring
people:
  principal_investigator:
    name: Yoonyoung Chung
    title: Professor
    desc: Ph.D., Electrical Engineering, Stanford University (2012)
    #thumb: ../metronic/assets/pages/img/people/img5-large.jpg
    social:
      email: ychung@postech.ac.kr
  graduate_students:
    - name: Juyoung Yun
      title: Graduate students
      desc: |
        B.S., Electrical Engineering, Kyungpook National University (2019)
        Research interest: 
      social:
        email: jpjeung@postech.ac.kr
    - name: Hyungmin Ko
      title: Graduate students
      desc: |
        B.S., Electrical Engineering, Kookmin University (2018)
        Research interest: 
      social:
        email: gudals0327@gmail.com
    - name: Taewon Seo
      title: Graduate students
      desc: |
        B.S., Electrical Engineering, POSTECH (2018)
        Research interest: 
      social:
        email: mjionunt02@postech.ac.kr
    - name: Jinpyeo Jeung
      title: Graduate students
      desc: |
        B.S., Electrical Engineering, POSTECH (2018)
        Research interest: Skin attachable sensors; surface electrode
        LG Display, Intern (Summer 2016)
      social:
        email: jpjeung@postech.ac.kr
    - name: Seongmin Park
      title: Graduate students
      desc: |
        B.S., Electrical Engineering, POSTECH (2016)
        Research interest: Flexible full-color electronic paper; novel 3-D flexible circuit
        LG Display, Intern (Summer 2016)
        SK Hynix, Intern (Winter 2014)
      social:
        email: psm918@postech.ac.kr
    - name: Inyeol Yun
      title: Graduate students
      desc: |
        M.S., Electrical Engineering, POSTECH (2018)
        B.S., Electrical Engineering, POSTECH (2016)
        Research interest: Skin attachable sensors; electrical stimulation for healthcare applications
        SK Hynix, Intern (Winter 2014)
      social:
        email: inyul1225@postech.ac.kr
    - name: Hyuk Park
      title: Graduate students
      desc: |
        B.S., Electrical Engineering, POSTECH (2016)
        Research interest: Novel fabrication process for flexible thin-film transistor; flexible active lens for the next generation wireless technology
      social:
        email: sksqkrgur@postech.ac.kr
    - name: Si Young Lee
      title: Graduate students
      desc: |
        Co-advised with Prof. Kilwon Cho (Chemical Engineering, principal advisor)
        Research interest: flexible MEMS, wearable sensor
        B.S., Chemical Engineering, POSTECH (2014)
      social:
        email: challenge@postech.ac.kr
    - name: Seong Won Kim
      title: Graduate students
      desc: |
        Co-advised with Prof. Kilwon Cho (Chemical Engineering, principal advisor)
        Research interest: stretchable electrode for human–electronics interface
        B.S., Chemical Engineering, POSTECH (2014)
      social:
        email: ksw1118@postech.ac.kr
  cur_interns:
    - name: Yunsik Kim
      desc: POSTECH EE, Winter 2018
  prev_interns:
    - name: Yunsik Kim
      desc: POSTECH EE, Summer 2018
    - name: Gilsu Jeon
      desc: POSTECH EE, Summer 2018
    - name: Hyung Min Ko
      desc: Kookmin University EE, Summer 2018
    - name: Gwon Kim
      desc: Korea University EE, Summer 2018
    - name: Jueun Kim
      desc: Handong University EE, Summer 2018
    - name: Yong Hun Song
      desc: Kyunghee University EE, Summer 2018
    - name: Ju Young Yun
      desc: Kyungpook National University EE, Summer 2018
    - name: Dongyoon Lee
      desc: POSTECH EE, Winter 2017
    - name: Haeran Cho
      desc: Korea University EE, Winter 2017
    - name: Taewon Seo
      desc: POSTECH EE, Fall 2017
    - name: Jaeryung Han
      desc: Pusan National University OME, Winter 2017
    - name: Minji Park
      desc: POSTECH EE, Fall 2017
    - name: Suwon Seong
      desc: University of Seoul ECE, Summer 2017
    - name: Taehyoung Lim
      desc: POSTECH EE, Spring 2017
    - name: Suan Lee
      desc: POSTECH EE, Spring 2017)
    - name: Jihoon Park
      desc: Pusan National University OME, Winter 2016
    - name: Junseo Joe
      desc: POSTECH EE, Winter 2016–Spring 2017
    - name: Younghoon Byun
      desc: POSTECH EE, Winter 2016
    - name: Sejin Kim
      desc: Chonnam National University ECE, Fall 2016
    - name: Jinpyeo Jeung
      desc: POSTECH EE, Fall–Winter 2016
    - name: Tae Gyun Lee
      desc: Korea University EE, Summer 2016
    - name: Woojo Kim
      desc: Kyung Hee University ERE, Spring 2016
    - name: Young-Uk Shin
      desc: Kyungpook National University EE, Summer 2016
    - name: Seongmin Park
      desc: POSTECH EE, Winter 2015–Spring 2016
    - name: Hyounglae Kim
      desc: POSTECH EE, Winter 2015
    - name: Sukjun Kang
      desc: POSTECH EE, Winter 2015
    - name: Won Kyung Jung
      desc: POSTECH EE, Winter 2015
    - name: Insung Ahn
      desc: POSTECH EE, Winter 2015
    - name: Inyeol Yun
      desc: POSTECH EE, Summer–Fall 2015
    - name: Seunglok Song
      desc: POSTECH EE, Summer 2015
    - name: Jeong Woo Park
      desc: Kyung Hee University ERE, Summer 2015
    - name: Hyuk Park
      desc: POSTECH EE, Summer–Fall 2015
    - name: Miram Kwon
      desc: Soongsil University EE, Summer 2015
    - name: Subon Kim
      desc: Hanyang University MSE, Summer 2015
    - name: Dong Hyup Kim
      desc: Hanyang University EE, Summer 2015
    - name: Jiho Choi
      desc: Hanyang University EE, Summer 2015
